### ISSUE TITLE
Fix the onboarding buttons

### ISSUE THREAD

**Issue by meri-nova** [meri-nova/Break-Into-Data-Discord-Bot#17]
After sometime the buttons on the onboarding form are not working. 

Need to fix. 

Before we onboard everyone on the server. 

<img width="567" alt="Screen Shot 2024-02-15 at 5 10 23 PM" src="https://github.com/meri-nova/discord/assets/44347897/f542bdbf-f27b-4cd9-a39e-969633c1ec10">

**Comment by KostyaCholak** [comment]
Discord view have 3 minute timeouts by default 😕
fix: https://github.com/meri-nova/Break-Into-Data-Discord-Bot/pull/18
